Separate start/stop from whitelist
Starting and stopping the firewall is now completely independant of the
whitelist handling. On boot the firewall is only started without the
whitelist. The whitelist is only (re)loaded on interface status changes.
The firewall itself (beside the whitelist) is not changed on these
events.

diff --git a/debian/lernstick-firewall.init b/debian/lernstick-firewall.init
--- a/debian/lernstick-firewall.init
+++ b/debian/lernstick-firewall.init
@@ -135,8 +135,8 @@ do_reload()
 {
     RETVAL="0"
 
-    log_daemon_msg "Reloading $DESC" "iptables"
-    ${FIREWALL} reload || RETVAL="2"
+    [ "$VERBOSE" != no ] && log_daemon_msg "Reloading $DESC" "whitelist"
+    ${FIREWALL} reload-whitelist || RETVAL="2"
 
     log_progress_msg "tinyproxy"
     start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name tinyproxy || RETVAL="2"
@@ -161,7 +161,18 @@ case "$1" in
         do_stop
         ;;
     status)
-        status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+        if ${FIREWALL} status ; then
+            [ "$VERBOSE" != no ] && log_success_msg "Firewall active"
+            RETVAL=0
+        else
+            [ "$VERBOSE" != no ] && log_failure_msg "Firewall not active"
+            RETVAL=1
+        fi
+        if ! status_of_proc "$TINYPROXY" "tinyproxy" ; then
+            # only change return value if tinyproxy is not running
+            RETVAL=$?
+        fi
+        exit $RETVAL
         ;;
     reload|force-reload)
         do_reload
